---
title: "Diversehandel"
output: html_document
---
<body style="background-color:powderblue;">

<h1>  </h1>
<style>
h1 {text-align: center;}
</style>


## 
<h2> Matematik </h2>
###   Linjär algebra
####   Bok i linjär algebra: [Bok/pdf](cognitrap.github.io/Matematik/Linjär_Algebra/LA1.pdf)
#### Illustrationer: [Illustrationer/mybinder]( https://mybinder.org/v2/gh/cognitrap/LA/Illustr/master?filepath=index.ipynb)
#### Projektuppgifter: [Uppgifter/mybinder]( https://mybinder.org/v2/gh/cognitrap/LA/master?filepath=index.ipynb)
####  Resurs till Bok: [Del2](cognitrap.github.io/Matematik/Linjär_Algebra/Del2.pdf)



###   Flerdimensionell analys

<!--[Geogebrafiler](cognitrap.github.io/Matematik/Flervariabelanalys/Geogebrafiler/ggbfiler.html) -->


#### <!-- -->
<hr>


<h2> Fysik </h2>

###    Långsam fysikkurs
#### Rörelsebegrepp: [Movement](cognitrap.github.io/Fysik/LångsamFysikkurs/Movement.pdf)

#### Kraftbegrepp: [Force](cognitrap.github.io/Fysik/LångsamFysikkurs/Force.pdf)

#### Rörelsemängd: [Momentum](cognitrap.github.io/Fysik/LångsamFysikkurs/Momentum.pdf)

#### Kaströrelse: [Projectile](cognitrap.github.io/Fysik/LångsamFysikkurs/Projectile.pdf)

#### Rotationsrörelse: [Rotation](cognitrap.github.io/Fysik/LångsamFysikkurs/Rotation.pdf)


#### <!-- -->
#### <!-- -->

<hr>

<h2> Programmering </h2>

#### Materialet är byggt med hjälp av jupyter notebook. Värden för detta ligger på ett annat ställe
#### men det är bara att klicka på länken: [Python/Jupyter]( https://mybinder.org/v2/gh/cognitrap/progr/master?filepath=index.ipynb).

<footer>&copy; Leif Karlsson 2021 </footer>
</body>
